[package]
name = "crust-utils"
version = "0.1.0"
authors = ["Moritz Baeumel <moritzbaeumnel@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.4.3"
dioxus-desktop = "0.4.3"
