name: lint

on: 
  pull_request:
  push:
    branches: [ "main" ]

jobs:

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with: 
          toolchain: stable
          components: rustfmt
      - run: cargo fmt -- --check
  
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with: 
          toolchain: stable
          components: clippy
      - run: |
          sudo apt-get install libgtk-3-dev\
           libsoup-3.0\
           javascriptcoregtk-4.1\
           webkit2gtk-4.1
      - run: cargo clippy --all-targets -- -D warnings
  
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with: 
          toolchain: stable
      - run: |
          sudo apt-get install libgtk-3-dev\
           libsoup-3.0\
           javascriptcoregtk-4.1\
           webkit2gtk-4.1
      - run: cargo build
